export const ALL_PERMISSIONS = {
    PATIENTS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/patients', module: "PATIENTS" },
        CREATE: { method: "POST", apiPath: '/api/v1/patients', module: "PATIENTS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/patients/{id}', module: "PATIENTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/patients/{id}', module: "PATIENTS" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/patients/{id}', module: "PATIENTS" },
    },
    PERMISSIONS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/permissions', module: "PERMISSIONS" },
        CREATE: { method: "POST", apiPath: '/api/v1/permissions', module: "PERMISSIONS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/permissions', module: "PERMISSIONS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/permissions/{id}', module: "PERMISSIONS" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/permissions/{id}', module: "PERMISSIONS" },
    },
    ROLES: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/roles', module: "ROLES" },
        CREATE: { method: "POST", apiPath: '/api/v1/roles', module: "ROLES" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/roles', module: "ROLES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/roles/{id}', module: "ROLES" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/role/{id}', module: "ROLES" },
    },
    USERS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/users', module: "USERS" },
        CREATE: { method: "POST", apiPath: '/api/v1/users', module: "USERS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/users', module: "USERS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/users/{id}', module: "USERS" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/user/{id}', module: "USERS" },
    },
    EPISODES: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/episodes', module: "EPISODES" },
        CREATE: { method: "POST", apiPath: '/api/v1/episodes', module: "EPISODES" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/episodes/{id}', module: "EPISODES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/episodes/{id}', module: "EPISODES" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/episodes/{id}', module: "EPISODES" },
        GET_BY_PATIENT: { method: "GET", apiPath: '/api/v1/patients/{patientId}/episodes', module: "EPISODES" },
    },
    CLINICAL_RECORDS: {
        CREATE: { method: "POST", apiPath: '/api/v1/clinical-records', module: "CLINICAL_RECORDS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/clinical-records/{id}', module: "CLINICAL_RECORDS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/clinical-records/{id}', module: "CLINICAL_RECORDS" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/clinical-records/{id}', module: "CLINICAL_RECORDS" },
        GET_BY_EPISODE: { method: "GET", apiPath: '/api/v1/episodes/{episodeId}/clinical-records', module: "CLINICAL_RECORDS" },
    },
    SURGERIES: {
        CREATE: { method: "POST", apiPath: '/api/v1/surgeries', module: "SURGERIES" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/surgeries/{id}', module: "SURGERIES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/surgeries/{id}', module: "SURGERIES" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/surgeries/{id}', module: "SURGERIES" },
        GET_BY_EPISODE: { method: "GET", apiPath: '/api/v1/episodes/{episodeId}/surgeries', module: "SURGERIES" },
    },
    LAB_RESULTS: {
        CREATE: { method: "POST", apiPath: '/api/v1/lab-results', module: "LAB_RESULTS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/lab-results/{id}', module: "LAB_RESULTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/lab-results/{id}', module: "LAB_RESULTS" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/lab-results/{id}', module: "LAB_RESULTS" },
        GET_BY_EPISODE: { method: "GET", apiPath: '/api/v1/episodes/{episodeId}/lab-results', module: "LAB_RESULTS" },
    },
    IMAGE_RESULTS: {
        CREATE: { method: "POST", apiPath: '/api/v1/image-results', module: "IMAGE_RESULTS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/image-results/{id}', module: "IMAGE_RESULTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/image-results/{id}', module: "IMAGE_RESULTS" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/image-results/{id}', module: "IMAGE_RESULTS" },
        GET_BY_EPISODE: { method: "GET", apiPath: '/api/v1/episodes/{episodeId}/image-results', module: "IMAGE_RESULTS" },
    },
    CULTURE_RESULTS: {
        CREATE: { method: "POST", apiPath: '/api/v1/culture-results', module: "CULTURE_RESULTS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/culture-results/{id}', module: "CULTURE_RESULTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/culture-results/{id}', module: "CULTURE_RESULTS" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/culture-results/{id}', module: "CULTURE_RESULTS" },
        GET_BY_EPISODE: { method: "GET", apiPath: '/api/v1/episodes/{episodeId}/culture-results', module: "CULTURE_RESULTS" },
    },
    SENSITIVITY_RESULTS: {
        CREATE: { method: "POST", apiPath: '/api/v1/sensitivity-results', module: "SENSITIVITY_RESULTS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/sensitivity-results/{id}', module: "SENSITIVITY_RESULTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/sensitivity-results/{id}', module: "SENSITIVITY_RESULTS" },
        GET_BY_ID: { method: "GET", apiPath: '/api/v1/sensitivity-results/{id}', module: "SENSITIVITY_RESULTS" },
        GET_BY_CULTURE: { method: "GET", apiPath: '/api/v1/culture-results/{cultureId}/sensitivity-results', module: "SENSITIVITY_RESULTS" },
    },
    MEDICAL_HISTORY: {
        CREATE: { method: "POST", apiPath: '/api/v1/episodes/{episodeId}/medical-history', module: "MEDICAL_HISTORY" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/episodes/{episodeId}/medical-history', module: "MEDICAL_HISTORY" },
        GET: { method: "GET", apiPath: '/api/v1/episodes/{episodeId}/medical-history', module: "MEDICAL_HISTORY" },
    },
    RAG: {
        GENERATE: { method: "POST", apiPath: '/api/v1/episodes/{episodeId}/ai-recommendations/generate', module: "RAG" },
        GENERATE_SYNC: { method: "POST", apiPath: '/api/v1/episodes/{episodeId}/ai-recommendations/generate-sync', module: "RAG" },
        GET_RUNS: { method: "GET", apiPath: '/api/v1/episodes/{episodeId}/ai-recommendations/runs', module: "RAG" },
        GET_RUN_DETAIL: { method: "GET", apiPath: '/api/v1/ai-recommendations/runs/{runId}', module: "RAG" },
        RETRY_RUN: { method: "POST", apiPath: '/api/v1/ai-recommendations/runs/{runId}/retry', module: "RAG" },
        STREAM_LOGS: { method: "GET", apiPath: '/api/v1/ai-recommendations/runs/{runId}/stream', module: "RAG" },
    },
    AI_CHAT: {
        CREATE_SESSION: { method: "POST", apiPath: '/api/v1/ai-chat/sessions', module: "AI_CHAT" },
        SEND_MESSAGE: { method: "POST", apiPath: '/api/v1/ai-chat/sessions/{sessionId}/messages', module: "AI_CHAT" },
        GET_MESSAGES: { method: "GET", apiPath: '/api/v1/ai-chat/sessions/{sessionId}/messages', module: "AI_CHAT" },
        GET_SESSIONS: { method: "GET", apiPath: '/api/v1/episodes/{episodeId}/ai-chat/sessions', module: "AI_CHAT" },
    },
    DOCTOR_REVIEWS: {
        CREATE: { method: "POST", apiPath: '/api/v1/episodes/{episodeId}/doctor-reviews', module: "DOCTOR_REVIEWS" },
        GET_BY_RUN: { method: "GET", apiPath: '/api/v1/ai-recommendations/runs/{runId}/review', module: "DOCTOR_REVIEWS" },
        GET_BY_EPISODE: { method: "GET", apiPath: '/api/v1/episodes/{episodeId}/doctor-reviews', module: "DOCTOR_REVIEWS" },
        GET_FINAL_DECISION: { method: "GET", apiPath: '/api/v1/episodes/{episodeId}/doctor-reviews/final-decision', module: "DOCTOR_REVIEWS" },
        SELECT_FINAL_DECISION: { method: "PUT", apiPath: '/api/v1/episodes/{episodeId}/doctor-reviews/{reviewId}/final-decision', module: "DOCTOR_REVIEWS" },
    },
    CLINICAL_DECISIONS: {
        GET_WORKSPACE: { method: "GET", apiPath: '/api/v1/episodes/{episodeId}/clinical-decisions/workspace', module: "CLINICAL_DECISIONS" },
        GET_RUN: { method: "GET", apiPath: '/api/v1/ai-recommendations/runs/{runId}/clinical-decisions', module: "CLINICAL_DECISIONS" },
        SAVE_DOCTOR: { method: "PUT", apiPath: '/api/v1/ai-recommendations/runs/{runId}/doctor-decision', module: "CLINICAL_DECISIONS" },
        SIGN_DOCTOR: { method: "POST", apiPath: '/api/v1/ai-recommendations/runs/{runId}/doctor-decision/sign', module: "CLINICAL_DECISIONS" },
        SAVE_PHARMACIST: { method: "PUT", apiPath: '/api/v1/ai-recommendations/runs/{runId}/pharmacist-decision', module: "CLINICAL_DECISIONS" },
        SIGN_PHARMACIST: { method: "POST", apiPath: '/api/v1/ai-recommendations/runs/{runId}/pharmacist-decision/sign', module: "CLINICAL_DECISIONS" },
        SELECT_FINAL: { method: "PUT", apiPath: '/api/v1/episodes/{episodeId}/clinical-decisions/final-run/{runId}', module: "CLINICAL_DECISIONS" },
    },
    PENDING_LAB_TASKS: {
        GET_MY: { method: "GET", apiPath: '/api/v1/pending-lab-tasks/my', module: "PENDING_LAB_TASKS" },
        GET_MY_COUNT: { method: "GET", apiPath: '/api/v1/pending-lab-tasks/my/count', module: "PENDING_LAB_TASKS" },
        DISMISS: { method: "POST", apiPath: '/api/v1/pending-lab-tasks/{id}/dismiss', module: "PENDING_LAB_TASKS" },
        QUICK_ENTRY: { method: "POST", apiPath: '/api/v1/pending-lab-tasks/{id}/quick-entry', module: "PENDING_LAB_TASKS" },
        CREATE_FROM_COMPLETENESS: { method: "POST", apiPath: '/api/v1/episodes/{episodeId}/pending-lab-tasks/from-completeness', module: "PENDING_LAB_TASKS" },
    },
    EXTRACT_IMAGES: {
        CREATE_JOB: { method: "POST", apiPath: '/api/v1/extract-images/jobs', module: "EXTRACT_IMAGES" },
        GET_JOB: { method: "GET", apiPath: '/api/v1/extract-images/jobs/{jobId}', module: "EXTRACT_IMAGES" },
    },
    FILES: {
        UPLOAD: { method: "POST", apiPath: '/api/v1/files', module: "FILES" },
    },
    NOTIFICATIONS: {
        GET_MY: { method: "GET", apiPath: '/api/v1/notifications', module: "NOTIFICATIONS" },
        GET_UNREAD_COUNT: { method: "GET", apiPath: '/api/v1/notifications/unread-count', module: "NOTIFICATIONS" },
        MARK_READ: { method: "PATCH", apiPath: '/api/v1/notifications/{id}/read', module: "NOTIFICATIONS" },
        MARK_ALL_READ: { method: "POST", apiPath: '/api/v1/notifications/mark-all-read', module: "NOTIFICATIONS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/notifications', module: "NOTIFICATIONS" },
    },
};
