import { CSSProperties } from "react";

export const pageStyles: Record<string, CSSProperties> = {
    page: {
        minHeight: '100%',
        background: '#edf0f4',
        padding: '10px 18px 32px',
        overflowY: 'auto',
    },
    shell: {
        width: '100%',
        maxWidth: 1040,
        margin: '0 auto',
    },
    header: {
        background: '#fffefe',
        marginBottom: 16,
        padding: '15px 15px',
    },
    title: {
        margin: 0,
        color: '#111827',
        fontSize: 22,
        lineHeight: 1.25,
        fontWeight: 800,
    },
    resultCard: {
        width: 272,
        borderColor: '#ffccc7',
        background: '#fff1f0',
        borderRadius: 8,
        boxShadow: 'none',
    },
    resultCardBody: {
        padding: '14px 20px',
    },
    resultGrid: {
        display: 'grid',
        gridTemplateColumns: '1fr auto 1fr',
        gap: 18,
        alignItems: 'center',
    },
    resultLabel: {
        display: 'block',
        color: '#6b7280',
        fontSize: 12,
        lineHeight: 1.2,
        marginBottom: 4,
    },
    scoreCard: {
        borderRadius: 8,
        border: '1px solid #e5e7eb',
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.05)',
        marginBottom: 14,
    },
    scoreCardBody: {
        padding: '20px 24px',
    },
    scoreTitle: {
        margin: 0,
        fontSize: 15,
        color: '#111827',
        fontWeight: 800,
    },
    scoreRailArea: {
        position: 'relative',
        paddingTop: 30,
        marginTop: 6,
    },
    scoreRail: {
        height: 8,
        borderRadius: 999,
        background: 'linear-gradient(90deg, #9fe58c 0%, #9fe58c 25%, #ffd979 25%, #ffd979 50%, #ffb9b3 50%, #ffb9b3 100%)',
    },
    scoreLabels: {
        display: 'flex',
        justifyContent: 'space-between',
        color: '#8b95a5',
        fontFamily: 'Consolas, Monaco, monospace',
        fontSize: 12,
        marginTop: 9,
    },
    scoreMarker: {
        position: 'absolute',
        top: 8,
        transform: 'translateX(-50%)',
        textAlign: 'center',
        color: '#26375e',
        fontSize: 15,
        fontWeight: 700,
        whiteSpace: 'nowrap',
    },
    markerLine: {
        width: 2,
        height: 16,
        background: '#1f2937',
        margin: '3px auto 0',
    },
    organismRow: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 16,
        flexWrap: 'wrap',
        minHeight: 38,
    },
    organismLeft: {
        display: 'flex',
        alignItems: 'center',
        gap: 12,
        flex: '1 1 280px',
        minWidth: 0,
    },
    organismName: {
        fontSize: 14,
        fontWeight: 800,
        color: '#111827',
    },
    organismDetail: {
        color: '#5b6472',
        fontFamily: 'Consolas, Monaco, monospace',
        fontSize: 12,
        flex: '1 1 240px',
        textAlign: 'right',
    },
    warningAlert: {
        borderColor: '#ffd666',
        background: '#fffbe6',
        borderRadius: 8,
    },
    criteriaCard: {
        height: '100%',
        borderRadius: 8,
        border: '1px solid #e5e7eb',
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.05)',
    },
    criteriaHeader: {
        padding: '16px 24px',
        borderBottom: '1px solid #eef0f3',
    },
    criteriaBody: {
        padding: '16px 24px 20px',
    },
    criteriaTitle: {
        margin: 0,
        color: '#111827',
        fontSize: 16,
        fontWeight: 800,
        lineHeight: 1.2,
    },
    criteriaSubtitle: {
        display: 'block',
        color: '#9ca3af',
        fontSize: 12,
        marginTop: 1,
    },
    note: {
        color: '#4b5563',
        fontSize: 13,
        lineHeight: 1.65,
        marginBottom: 12,
    },
    dashedDivider: {
        margin: '10px 0 14px',
        borderColor: '#d6d9de',
        borderStyle: 'dashed',
    },
    criterionItem: {
        border: '1px solid #e5e7eb',
        borderRadius: 5,
        padding: '11px 12px',
        marginBottom: 9,
        background: '#ffffff',
    },
    criterionRow: {
        display: 'flex',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        gap: 12,
    },
    criterionText: {
        fontSize: 13,
        color: '#111827',
        lineHeight: 1.45,
    },
    detailText: {
        display: 'block',
        marginTop: 10,
        fontSize: 12,
        lineHeight: 1.55,
    },
    minorItem: {
        border: '1px solid #e5e7eb',
        borderRadius: 5,
        padding: '11px 12px',
        marginBottom: 9,
        background: '#ffffff',
    },
    minorResult: {
        display: 'block',
        color: '#4b5563',
        fontFamily: 'Consolas, Monaco, monospace',
        fontSize: 12,
        lineHeight: 1.45,
        marginTop: 8,
    },
    actionBar: {
        display: 'flex',
        justifyContent: 'flex-end',
        gap: 10,
        marginTop: 18,
    },
    emptyWrap: {
        minHeight: 'calc(100vh - 220px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyCard: {
        width: '100%',
        maxWidth: 460,
        borderRadius: 8,
        border: '1px solid #e5e7eb',
    },
};