// Extracted from sheets 1 and 2, column "Tên vi khuẩn đầy đủ", in
// ds_vk_ks_nấm.xlsx.
const bacteriaNames = [
  'Escherichia coli',
  'Escherichia hermannii',
  'Klebsiella pneumoniae',
  'Klebsiella oxytoca',
  'Klebsiella variicola',
  'Klebsiella aerogenes (trước đây là Enterobacter aerogenes)',
  'Enterobacter cloacae complex',
  'Enterobacter asburiae',
  'Enterobacter hormaechei',
  'Enterobacter kobei',
  'Enterobacter ludwigii',
  'Citrobacter freundii',
  'Citrobacter koseri',
  'Citrobacter amalonaticus group (gồm C. amalonaticus, C. farmeri, C. sedlakii)',
  'Hafnia alvei',
  'Hafnia paralvei',
  'Morganella morganii',
  'Proteus mirabilis',
  'Proteus penneri',
  'Proteus vulgaris',
  'Providencia rettgeri',
  'Providencia stuartii',
  'Raoultella spp. (gồm R. ornithinolytica, R. terrigena, R. planticola)',
  'Salmonella spp. (kể cả Salmonella enterica ser. Typhi)',
  'Shigella spp.',
  'Serratia marcescens',
  'Yersinia enterocolitica',
  'Pseudomonas aeruginosa',
  'Acinetobacter baumannii / Acinetobacter calcoaceticus complex',
  'Burkholderia cepacia complex',
  'Stenotrophomonas maltophilia',
  'Haemophilus influenzae',
  'Haemophilus parainfluenzae',
  'Neisseria gonorrhoeae',
  'Neisseria meningitidis',
  'Bacteroides fragilis',
  'Bacteroides thetaiotaomicron',
  'Bacteroides spp.',
  'Fusobacterium canifelinum',
  'Staphylococcus aureus',
  'Staphylococcus lugdunensis',
  'Staphylococcus epidermidis',
  'Staphylococcus haemolyticus',
  'Staphylococcus saprophyticus',
  'Staphylococcus capitis',
  'Staphylococcus cohnii',
  'Staphylococcus xylosus',
  'Enterococcus faecalis',
  'Enterococcus faecium',
  'Enterococcus gallinarum',
  'Enterococcus casseliflavus',
  'Streptococcus pneumoniae',
  'Streptococcus spp. nhóm β-tan huyết (β-Hemolytic Group)',
  'Streptococcus spp. nhóm Viridans (Viridans Group)',
  'Clostridioides difficile (trước đây là Clostridium difficile)',
  'Clostridium innocuum',
  'Clostridium spp. và Clostridioides spp.',
  'Eggerthella lenta (trước đây là Eubacterium lentum)',
] as const;

export const bacteriaNameOptions = bacteriaNames.map((value) => ({ value }));
